### ISSUE TITLE
[Bug] Running on Proxmox host produces timeout error on startup

### ISSUE THREAD

**Issue by brabulla** [christomitov/soundbored#13]
I've ran the app successfully from my main PC, running windows, and it successfully connected to a discord channel, and I was able to play sounds.

But now I'm trying to run the app from a Proxmox LXC container on my server, on the same network as my PC, and I'm receiving the following error on startup:

soundbored_1  | 00:00:43.920 [info] Migrations already up
soundbored_1  | Starting Phoenix server...
soundbored_1  | + echo 'Starting Phoenix server...'
soundbored_1  | + exec mix phx.server
soundbored_1  | 00:00:54.958 [error] ** State machine 'Elixir.Nostrum.Api.Ratelimiter' terminating
soundbored_1  | ** Last event = {state_timeout,connect_timeout}
soundbored_1  | ** When server state  = {connecting,#{running => #{},
soundbored_1  |                                       remaining_in_window => 50,
soundbored_1  |                                       outstanding => #{},
soundbored_1  |                                       wrapped_token =>
soundbored_1  |                                           #Fun<Elixir.Nostrum.Api.Ratelimiter.4.93930539>,
soundbored_1  |                                       conn => <0.235.0>,inflight => #{}}}
soundbored_1  | ** Reason for termination = exit:connect_timeout
soundbored_1  | ** Callback modules = ['Elixir.Nostrum.Api.Ratelimiter']
soundbored_1  | ** Callback mode = state_functions
soundbored_1  | ** Postponed = [{{call,{<0.219.0>,#Ref<0.426245097.121372673.182969>}},
soundbored_1  |                  {queue,#{params => [],body => <<>>,
soundbored_1  |                           headers =>
soundbored_1  |                               [{<<"content-type">>,<<"application/json">>}],
soundbored_1  |                           method => get,route => <<"/gateway/bot">>}}}]
soundbored_1  | ** Stacktrace =
soundbored_1  | **  [{gen_statem,loop_state_callback_result,11,
soundbored_1  |                  [{file,"gen_statem.erl"},{line,3857}]},
soundbored_1  |      {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,329}]}]
soundbored_1  | 
soundbored_1  | 00:00:54.965 [notice] Application nostrum exited: Nostrum.Application.start(:normal, []) returned an error: shutdown: failed to start child: Nostrum.Shard.Supervisor
soundbored_1  |     ** (EXIT) exited in: :gen_statem.call(#PID<0.225.0>, {:queue, %{params: [], body: "", headers: [{"content-type", "application/json"}], method: :get, route: "/gateway/bot"}}, :infinity)
soundbored_1  |         ** (EXIT) :connect_timeout
soundbored_1  | ** (exit) :terminating
soundbored_1  |     (kernel 10.2) application_controller.erl:511: :application_controller.call/2
soundbored_1  |     (kernel 10.2) application.erl:367: :application."-ensure_all_started/3-lc$^0/1-0-"/1
soundbored_1  |     (kernel 10.2) application.erl:367: :application.ensure_all_started/3
soundbored_1  |     (mix 1.18.0) lib/mix/tasks/app.start.ex:72: Mix.Tasks.App.Start.start/3
soundbored_1  |     (mix 1.18.0) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
soundbored_1  |     (mix 1.18.0) lib/mix/tasks/run.ex:129: Mix.Tasks.Run.run/5
soundbored_1  |     (mix 1.18.0) lib/mix/tasks/run.ex:85: Mix.Tasks.Run.run/1
soundbored_1  |     (mix 1.18.0) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5

I have not seen any parts in the code that reference the /gateway/bot URL, so I'm assuming it is some kind of callback URL for authentication towards the Discord server.

I'm running the same image, with the same parameters on my server, yet I'm receiving the timeout error. 

Do you maybe have an idea what could be causing this? Or if there is any way I can increase logging, to show more info, or some other way to debug?

**Comment by christomitov** [comment]
How are you setting this up, can you run through what you did? I also use proxmox. Maybe i'll create a community script for this to make it easier.

Normally for this i just spin up a LXC container and use docker inside it

**Comment by brabulla** [comment]
I have a small server, which has Proxmox installed , and runs LXC Containers, each housing multiple docker containers. 

I also have a reverse proxy, with cert management, which I would hope to use with Soundbored, so I'm trying to deploy without Caddy .

I usually deploy services through Portainer, using stacks, but deploying Soundbored through it lead to the same error.
I also tried to deploy from the command line, with docker compose, and received the error I pasted in the initial post. 

I've tried to authenticate towards Discord from the same machine, from a different container, using python, with some example code, and it seemed to be able to authenticate (though it only used the token, without the client secret / id)


This is the docker-compose file I'm using:
```
version: '3'
services:
  soundbored:
    image: christom/soundbored:latest
    ports:
      - "24000:4000"
    environment:
      API_TOKEN: ${API_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MIX_ENV: ${MIX_ENV}
      PHX_HOST: ${PHX_HOST}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SCHEME: ${SCHEME}
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    volumes:
      - soundbored_data:/app/priv/static/uploads
    env_file: .env

volumes:
  soundbored_data:
```

And the env file (removed the sensitive values):
```
# Discord Bot Configuration
DISCORD_TOKEN=
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
# Basic Auth
BASIC_AUTH_USERNAME=
BASIC_AUTH_PASSWORD=

# Application Configuration
PHX_HOST=localhost
SCHEME=http


# Docker Configuration
COMPOSE_PROJECT_NAME=soundbored
MIX_ENV=prod
```

Discord values I use should be fine, and the bot should be correctly configured, since I was able to run the same from my Windows PC.
