### ISSUE TITLE
Mounting Storage

### ISSUE THREAD

**Issue by nealhead** [christomitov/soundbored#3]
Is it possible to mount storage for where sound clips are stored?

Use case is I am using this on Unraid and I don't want my docker image to be filled up by sound clips :)

**Comment by christomitov** [comment]
Hey,

Assuming this path is accessible on the host running docker, here's how you can do it with a bind mount. I would grab whats in the docker right now in `/app/priv/static/uploads` and move it to your new path. Then it's just a matter of pointing it as below:

```
services:
  soundbored:
    image: christom/soundbored:latest
    ports:
      - "4000:4000"
    environment:
      API_TOKEN: ${API_TOKEN}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MIX_ENV: ${MIX_ENV:-prod}
      PHX_HOST: ${PHX_HOST:-localhost}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      SCHEME: ${SCHEME:-http}
      BASIC_AUTH_USERNAME: ${BASIC_AUTH_USERNAME}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
    volumes:
      - /path/to/host/directory:/app/priv/static/uploads
    env_file: .env

# Remove the volumes section if not needed
# volumes:
#   soundbored_data:
```
